######################################################################
##
## Filename: aluw1.udo
## Created on: Sun Sep 07 18:40:38 Kaliningrad Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
