######################################################################
##
## Filename: aluw4test.udo
## Created on: Sun Sep 07 21:10:32 Kaliningrad Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
