######################################################################
##
## Filename: aluw1test.udo
## Created on: Sun Sep 07 20:33:21 Kaliningrad Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
